services:
  redis_db:
    image: redis:alpine
    container_name: quake_redis
    restart: unless-stopped

  quake_server:
    image: jamesla/quakelive:latest
    container_name: quake_live_server
    stdin_open: true
    tty: true

    ports:
      - "27960:27960/udp"
    depends_on:
      - redis_db

    volumes:
      - ./plugins:/qlds/minqlx-plugins
      - ./mapuche_aliases.json:/qlds/minqlx-plugins/mapuche_aliases.json
      - ./lmsound_map.json:/qlds/minqlx-plugins/lmsound_map.json
      - ./lm.factories:/qlds/baseq3/scripts/lm.factories
      - ./steamapps:/qlds/steamapps

    environment:
      ACCESS: |
        76561198257667410|5
        76561198014448247|5
        76561198015775820|5
        76561198045070268|5
        76561198257902041|5
        76561198261371023|5
        76561198282206581|5

      MINQLX_PLUGINS_GIT: "https://github.com/MinoMe/minqlx-plugins.git"

      WORKSHOP_IDS: |
        1229285077
        1229646043
        1232367617
        1581081443
        1631845548
        1788666539
        1865499301
        2237187647
        539421606
        545699336
        546129401
        546209430
        546895198
        546960020
        589313020
        610690400
        610698932
        641686200
        704683793
        733837124
        750877012
        941765259

      SERVER_CFG: |
        set sv_hostname "${SERVER_HOSTNAME}"
        set sv_maxClients "${MAX_CLIENTS}"
        set sv_privateClients "${MAX_CLIENTS}"
        set sv_privatePassword "${PRIVATE_PASSWORD}"
        set sv_fps "40"

        set rcon_password "${RCON_PASSWORD}"
        set g_password ""
        set g_gametype "0"
        set serverstartup "startrandommap"

        set rate "25000"
        set snaps "40"
        set com_maxfps "125"

        set qlx_owner "${QLX_OWNER}"
        set qlx_plugins "essentials,motd,fun,lmsound,mapuche"
        set qlx_redisAddress "redis_db:6379"
        set qlx_redisDatabase "0"

      MAP_POOL: |
        duelingkeeps|lmctf
        campgrounds|ffa
        overkill|ffa
        bloodrun|ffa

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
